# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CellsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='Del')),
                ('barcode', models.CharField(max_length=20, verbose_name='BarCode')),
                ('sample', models.SmallIntegerField(verbose_name='SampleNo.')),
            ],
            options={
                'verbose_name': 'CellInfo',
                'verbose_name_plural': 'CellsInfo',
                'db_table': 'emb_cells',
                'ordering': ['stage'],
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClustersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='Del')),
                ('name', models.CharField(max_length=20, verbose_name='CellType')),
            ],
            options={
                'verbose_name': 'Cluster',
                'db_table': 'emb_clusters',
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='Del')),
                ('expr', models.FloatField(verbose_name='Expression')),
                ('signify', models.BooleanField(default=0, verbose_name='Signify')),
                ('ctype', models.IntegerField(verbose_name='CellType')),
                ('cid', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='embdata.CellsInfo')),
            ],
            options={
                'verbose_name': 'Expression',
                'verbose_name_plural': 'Expression',
                'db_table': 'emb_expr',
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GenesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='Del')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('signify', models.BooleanField(default=0, verbose_name='Signify')),
                ('importance', models.FloatField(verbose_name='Importance')),
            ],
            options={
                'verbose_name': 'GeneInfo',
                'verbose_name_plural': 'GenesInfo',
                'db_table': 'emb_genes',
                'ordering': ['importance'],
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StagesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0, verbose_name='Del')),
                ('stage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'verbose_name': 'Stage[day]',
                'verbose_name_plural': 'Stages[day]',
                'db_table': 'emb_stages',
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='expression',
            name='gid',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, to='embdata.GenesInfo'),
        ),
        migrations.AddField(
            model_name='cellsinfo',
            name='stage',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='embdata.StagesInfo'),
        ),
        migrations.AddField(
            model_name='cellsinfo',
            name='type',
            field=models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='embdata.ClustersInfo'),
        ),
    ]
