# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-08 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesinfo',
            name='access',
            field=models.CharField(max_length=20, null=True, verbose_name='AccessNo.'),
        ),
    ]
