# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-08 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embdata', '0002_genesinfo_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genesinfo',
            name='importance',
            field=models.FloatField(default=0, verbose_name='Importance'),
        ),
    ]
